### ISSUE TITLE
How to convert NBT stored in drawers

### ISSUE THREAD

**Issue by edayot** [edayot/SimpleDrawer#27]
This is an item stored in a drawer before 24w09a :
![2024-03-02_10 43 00](https://github.com/edayot/SimpleDrawer/assets/35682876/d5438915-869d-4cfb-a19a-94f841dd9dbe)

This is the same item but in the new format : 
![2024-03-02_10 43 21](https://github.com/edayot/SimpleDrawer/assets/35682876/d331e05d-13b2-43f7-830e-02aa1e3d2e82)

It will be especially hard with others NBT components, like enchantments, custom data from others datapacks, copying them to the new format will be so hard to do.

**Comment by CptGummiball** [comment]
This is very annoying. Because new server versions will no longer be able to handle the old format at some point and all plugins and data packs that work with the old format will have to be rewritten. I'm already having a problem with it, especially because I want to export the nbt data. Now I have to convert the new data into an old format. If I find a way to ensure that it is recognized automatically and can also be applied to datapacks, I will be happy to let you know here.

**Comment by edayot** [comment]
Yeah everything will be in the "minecraft:custom_data" component, but I have to mimic the way items are transform at runtime.

Maybe by making a lib to do so ? idk

**Comment by CptGummiball** [comment]
Writin something for my plugin at this moment for it. And yes there will be a lib with some usual formats.

**Comment by edayot** [comment]
The drawers will **not** update from 1.20 to 1.21, this is too hard to do in datapacks
